[workspace]

members = [
  "zomes/profile"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hdk = {git ="https://github.com/holochain/holochain", rev = "a1206a694fe3b521440fe633db99a50b8255c1b2", package = "hdk"}
holochain_types = {git ="https://github.com/holochain/holochain", rev = "a1206a694fe3b521440fe633db99a50b8255c1b2", package = "holochain_types"}
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "v0.0.107-a1206", package = "hc_utils"}
