[workspace]

members = [
  "zomes/profile"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "03-12/hc-bump", package = "hc_utils"}
# hc_utils = { path = "../hc-utils/crates/hc-utils" }
hdk = {git = "https://github.com/holochain/holochain", rev = "a82372a62d46a503e48f345360d0fb18cc5822d1", package = "hdk"}
# hdk = { path = "../holochain/crates/hdk" }
