[workspace]

members = [
  "zomes/profile"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "v0.0.103", package = "hc_utils"}
# hc_utils = { path = "../hc-utils/crates/hc-utils" }
hdk = {git = "https://github.com/holochain/holochain", rev = "a8523568753bf7921f5cd90fd40e38402a6471b4", package = "hdk"}
# hdk = { path = "../holochain/crates/hdk" }
holo_hash = {git = "https://github.com/holochain/holochain", rev = "a8523568753bf7921f5cd90fd40e38402a6471b4", package = "holo_hash"}
