[workspace]
resolver = "2"

members = [
  "crates/membrane_manager_utils",
  "zomes/hc_cz_profile",
  "zomes/hc_iz_profile",
  "zomes/hc_iz_membrane_manager"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
