[workspace]

members = [
  "zomes/profile"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
# hc_utils = { path = "../hc-utils/crates/hc-utils" }
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "v0.0.102", package = "hc_utils"}
# hdk = { path = "../holochain/crates/hdk" }
hdk = {git = "https://github.com/holochain/holochain", rev = "8c85ba9629631a17b59b77b9a5a0d5f24c700d11", package = "hdk"}
