[workspace]

members = [
  "zomes/profile"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "gen", package = "hc_utils"}
# hc_utils = { path = "../hc-utils/crates/hc-utils" }
hdk = {git = "https://github.com/holochain/holochain", rev = "12e990f06b381b29b98f2c6bc15623af928d5787", package = "hdk"}
# hdk = { path = "../holochain/crates/hdk" }
