[workspace]

members = [
  "zomes/profile"
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
hc_utils = {git = "https://github.com/holochain/hc-utils", branch = "v0.0.107", package = "hc_utils"}
# hc_utils = { path = "../hc-utils/crates/hc-utils" }
hdk = {git = "https://github.com/holochain/holochain", rev = "ab02f36c87999d42026b7429164ded503bb39853", package = "hdk"}
# hdk = { path = "../holochain/crates/hdk" }
holo_hash = {git = "https://github.com/holochain/holochain", rev = "ab02f36c87999d42026b7429164ded503bb39853", package = "holo_hash"}
