[package]
name = "hc_joining_code"
version = "0.2.0"
authors = [ "zo-el<joelulahanna@gmail.com>" ]
edition = "2021"

[lib]
name = "hc_joining_code"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = { version = "=0.0.138", features = ["encoding"] }
serde = "1.0"
derive_more = "0.99"
