[package]
name = "membrane_manager_utils"
version = "0.1.0-beta-rc.3"
authors = [ "zo-el<joelulahanna@gmail.com>" ]
edition = "2021"

[lib]
name = "membrane_manager_utils"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "1.0"
derive_more = "=0.99.17"
hdi = "=0.2.0-beta-rc.3"
