[package]
name = "hc_iz_profile"
version = "0.1.0"
authors = ["zo-el <joelulahanna@gmail>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_iz_profile"

[dependencies]
serde = "1.0.139"
hdi = "=0.1.10"
