[package]
name = "membrane_manager_lib"
version = "0.1.0"
authors = ["zo-el <joelulahanna@gmail.com>"]
edition = "2021"

[lib]
name = "membrane_manager_lib"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
hdk = "=0.0.126"
hc_joining_code = {path = "../../crates/joining_code"}
