[package]
name = "profile"
version = "0.1.0"
authors = ["zo-el <joelulahanna@gmail>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profile"

[dependencies]
serde = "=1.0.123"
thiserror = "1.0.22"
hdk = "=0.0.115"
hc_utils = "=0.0.115"
