[package]
name = "profile"
version = "0.1.0"
authors = ["zo-el <joelulahanna@gmail>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "profile"

[dependencies]
serde = "1.0"
thiserror = "1.0"
hdk = { version = "=0.0.131" }
hc_utils = "=0.0.131"
